// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWYTcqz7T4gXOFWt0jdZ2KZIHLrQTXSI',
    appId: '1:148152873954:web:5cac8a3d4724957522ffbb',
    messagingSenderId: '148152873954',
    projectId: 'gesti-budget-theob',
    authDomain: 'gesti-budget-theob.firebaseapp.com',
    storageBucket: 'gesti-budget-theob.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClu4VTm232wJgITqd4iEYOh9OVt8KaHQg',
    appId: '1:148152873954:android:4df43b904bc38dfc22ffbb',
    messagingSenderId: '148152873954',
    projectId: 'gesti-budget-theob',
    storageBucket: 'gesti-budget-theob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAco7z1xSzph_DkOsZNeRG6ZewI2FYn5oo',
    appId: '1:148152873954:ios:58c3c8a1543abedf22ffbb',
    messagingSenderId: '148152873954',
    projectId: 'gesti-budget-theob',
    storageBucket: 'gesti-budget-theob.firebasestorage.app',
    iosBundleId: 'com.example.gestiBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAco7z1xSzph_DkOsZNeRG6ZewI2FYn5oo',
    appId: '1:148152873954:ios:58c3c8a1543abedf22ffbb',
    messagingSenderId: '148152873954',
    projectId: 'gesti-budget-theob',
    storageBucket: 'gesti-budget-theob.firebasestorage.app',
    iosBundleId: 'com.example.gestiBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXWYTcqz7T4gXOFWt0jdZ2KZIHLrQTXSI',
    appId: '1:148152873954:web:b96f435b098b7a4222ffbb',
    messagingSenderId: '148152873954',
    projectId: 'gesti-budget-theob',
    authDomain: 'gesti-budget-theob.firebaseapp.com',
    storageBucket: 'gesti-budget-theob.firebasestorage.app',
  );

}